// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbSeckillVoucher = "tb_seckill_voucher"

// TbSeckillVoucher mapped from table <tb_seckill_voucher>
type TbSeckillVoucher struct {
	VoucherID  uint64    `gorm:"column:voucher_id;type:bigint unsigned;primaryKey" json:"voucher_id"`                     // 关联的优惠券的id
	Stock      int64     `gorm:"column:stock;type:int;not null" json:"stock"`                                             // 库存
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	BeginTime  time.Time `gorm:"column:begin_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"begin_time"`   // 生效时间
	EndTime    time.Time `gorm:"column:end_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"end_time"`       // 失效时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName TbSeckillVoucher's table name
func (*TbSeckillVoucher) TableName() string {
	return TableNameTbSeckillVoucher
}
