// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbUserInfo = "tb_user_info"

// TbUserInfo mapped from table <tb_user_info>
type TbUserInfo struct {
	UserID     uint64    `gorm:"column:user_id;type:bigint unsigned;primaryKey;comment:主键，用户id" json:"user_id"`                        // 主键，用户id
	City       string    `gorm:"column:city;type:varchar(64);comment:城市名称" json:"city"`                                                // 城市名称
	Introduce  string    `gorm:"column:introduce;type:varchar(128);comment:个人介绍，不要超过128个字符" json:"introduce"`                          // 个人介绍，不要超过128个字符
	Fans       uint32    `gorm:"column:fans;type:int unsigned;comment:粉丝数量" json:"fans"`                                               // 粉丝数量
	Followee   uint32    `gorm:"column:followee;type:int unsigned;comment:关注的人的数量" json:"followee"`                                    // 关注的人的数量
	Gender     uint32    `gorm:"column:gender;type:tinyint unsigned;comment:性别，0：男，1：女" json:"gender"`                                 // 性别，0：男，1：女
	Birthday   time.Time `gorm:"column:birthday;type:date;comment:生日" json:"birthday"`                                                 // 生日
	Credits    uint32    `gorm:"column:credits;type:int unsigned;comment:积分" json:"credits"`                                           // 积分
	Level      uint32    `gorm:"column:level;type:tinyint unsigned;comment:会员级别，0~9级,0代表未开通会员" json:"level"`                           // 会员级别，0~9级,0代表未开通会员
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName TbUserInfo's table name
func (*TbUserInfo) TableName() string {
	return TableNameTbUserInfo
}
