// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbFollow = "tb_follow"

// TbFollow mapped from table <tb_follow>
type TbFollow struct {
	ID           int64     `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`                           // 主键
	UserID       uint64    `gorm:"column:user_id;type:bigint unsigned;not null" json:"user_id"`                             // 用户id
	FollowUserID uint64    `gorm:"column:follow_user_id;type:bigint unsigned;not null" json:"follow_user_id"`               // 关联的用户id
	CreateTime   time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
}

// TableName TbFollow's table name
func (*TbFollow) TableName() string {
	return TableNameTbFollow
}
