// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbUserInfo = "tb_user_info"

// TbUserInfo mapped from table <tb_user_info>
type TbUserInfo struct {
	UserID     uint64    `gorm:"column:user_id;type:bigint unsigned;primaryKey" json:"user_id"`                           // 主键，用户id
	City       string    `gorm:"column:city;type:varchar(64)" json:"city"`                                                // 城市名称
	Introduce  string    `gorm:"column:introduce;type:varchar(128)" json:"introduce"`                                     // 个人介绍，不要超过128个字符
	Fans       uint64    `gorm:"column:fans;type:int unsigned" json:"fans"`                                               // 粉丝数量
	Followee   uint64    `gorm:"column:followee;type:int unsigned" json:"followee"`                                       // 关注的人的数量
	Gender     uint8     `gorm:"column:gender;type:tinyint unsigned" json:"gender"`                                       // 性别，0：男，1：女
	Birthday   time.Time `gorm:"column:birthday;type:date" json:"birthday"`                                               // 生日
	Credits    uint64    `gorm:"column:credits;type:int unsigned" json:"credits"`                                         // 积分
	Level      uint8     `gorm:"column:level;type:tinyint unsigned" json:"level"`                                         // 会员级别，0~9级,0代表未开通会员
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName TbUserInfo's table name
func (*TbUserInfo) TableName() string {
	return TableNameTbUserInfo
}
