// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbSign = "tb_sign"

// TbSign mapped from table <tb_sign>
type TbSign struct {
	ID       uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	UserID   uint64    `gorm:"column:user_id;type:bigint unsigned;not null;comment:用户id" json:"user_id"`          // 用户id
	Year     int32     `gorm:"column:year;type:year;not null;comment:签到的年" json:"year"`                           // 签到的年
	Month    int32     `gorm:"column:month;type:tinyint;not null;comment:签到的月" json:"month"`                      // 签到的月
	Date     time.Time `gorm:"column:date;type:date;not null;comment:签到的日期" json:"date"`                          // 签到的日期
	IsBackup uint32    `gorm:"column:is_backup;type:tinyint unsigned;comment:是否补签" json:"is_backup"`              // 是否补签
}

// TableName TbSign's table name
func (*TbSign) TableName() string {
	return TableNameTbSign
}
