// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbShopType = "tb_shop_type"

// TbShopType mapped from table <tb_shop_type>
type TbShopType struct {
	ID         uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`           // 主键
	Name       string    `gorm:"column:name;type:varchar(32);comment:类型名称" json:"name"`                                       // 类型名称
	Icon       string    `gorm:"column:icon;type:varchar(255);comment:图标" json:"icon"`                                        // 图标
	Sort       uint32    `gorm:"column:sort;type:int unsigned;comment:顺序" json:"sort"`                                        // 顺序
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
}

// TableName TbShopType's table name
func (*TbShopType) TableName() string {
	return TableNameTbShopType
}
