// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTbShop = "tb_shop"

// TbShop mapped from table <tb_shop>
type TbShop struct {
	ID         uint64    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`         // 主键
	Name       string    `gorm:"column:name;type:varchar(128);not null" json:"name"`                             // 商铺名称
	TypeID     uint64    `gorm:"column:type_id;type:bigint unsigned;not null" json:"type_id"`                    // 商铺类型的id
	Images     string    `gorm:"column:images;type:varchar(1024);not null" json:"images"`                        // 商铺图片，多个图片以','隔开
	Area       string    `gorm:"column:area;type:varchar(128)" json:"area"`                                      // 商圈，例如陆家嘴
	Address    string    `gorm:"column:address;type:varchar(255);not null" json:"address"`                       // 地址
	X          float64   `gorm:"column:x;type:double unsigned;not null" json:"x"`                                // 经度
	Y          float64   `gorm:"column:y;type:double unsigned;not null" json:"y"`                                // 维度
	AvgPrice   uint64    `gorm:"column:avg_price;type:bigint unsigned" json:"avg_price"`                         // 均价，取整数
	Sold       uint64    `gorm:"column:sold;type:int(10) unsigned zerofill;not null" json:"sold"`                // 销量
	Comments   uint64    `gorm:"column:comments;type:int(10) unsigned zerofill;not null" json:"comments"`        // 评论数量
	Score      uint64    `gorm:"column:score;type:int(2) unsigned zerofill;not null" json:"score"`               // 评分，1~5分，乘10保存，避免小数
	OpenHours  string    `gorm:"column:open_hours;type:varchar(32)" json:"open_hours"`                           // 营业时间，例如 10:00-22:00
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;default:CURRENT_TIMESTAMP" json:"create_time"` // 创建时间
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;default:CURRENT_TIMESTAMP" json:"update_time"` // 更新时间
}

// TableName TbShop's table name
func (*TbShop) TableName() string {
	return TableNameTbShop
}
